# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt



    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: email
                class: AppBundle:Character
                property: name
                # if you're using multiple entity managers
                # manager_name: customer
        in_memory:
            memory: ~

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/char_select, roles: IS_AUTHENTICATED_FULLY }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            http_basic: ~
            provider: our_db_provider
            # activate different ways to authenticate

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                # default_target_path: char_select
                # là c'est pour envoyer sur un page après s'être log

            logout:
                path:   /logout
                target: /
